buildscript {
  repositories { mavenCentral() }
  dependencies {
    classpath("org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin:${kotlinVersion}")
  }
}

apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

group = 'com.folio.batterysync'
version = '0.1.0'

android {
  namespace 'com.folio.batterysync'
  buildFeatures { compose true }
  defaultConfig {
    minSdkVersion 28
    versionCode 1
    versionName '0.1.0'
  }
}

dependencies {
  implementation 'top.yukonga.miuix.kmp:miuix-android:0.7.2'
  implementation 'androidx.compose.foundation:foundation-android:1.9.3'
  implementation 'androidx.compose.ui:ui-android:1.9.3'
  implementation files('libs/xms-wearable-lib_1.4_release.aar')
  compileOnly files('libs/libxposed-api-102.0.0.aar')
  testImplementation 'junit:junit:4.13.2'
}
